
import java.awt.Color;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */

/**
 *
 * @author Asus
 */
public class SEARCH_COMPANY_DESIGN extends javax.swing.JPanel {

    /**
     * Creates new form SEARCH_COMPANY_DESIGN
     */
    public SEARCH_COMPANY_DESIGN() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        logo = new javax.swing.JLabel();
        name = new javax.swing.JLabel();

        setBackground(new Color(255,0,0,0));
        setForeground(new java.awt.Color(0, 0, 0));
        setLayout(null);

        logo.setText("jLabel1");
        add(logo);
        logo.setBounds(10, 20, 160, 160);

        name.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        name.setText("jLabel2");
        add(name);
        name.setBounds(220, 50, 400, 50);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JLabel logo;
    public javax.swing.JLabel name;
    // End of variables declaration//GEN-END:variables
}
